services:
  php:
    build:
      context: ./backend/Api
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./backend/Api:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ecoride
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
