services:
  db:
    image: mysql:8.0
    container_name: ecoride_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ecoride
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: ecoride_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root

  symfony:
    build:
      context: ./Backend
    container_name: ecoride_symfony
    depends_on:
      - db
    volumes:
      - ./Backend:/app
    working_dir: /app
    command: php -S 0.0.0.0:8000 -t public
    ports:
      - "8000:8000"

volumes:
  db_data:
