nelmio_cors:
  defaults:
    allow_credentials: true
    origin_regex: true
    allow_origin:
      - '^http://localhost(:[0-9]+)?$'
      - '^http://127\.0\.0\.1(:[0-9]+)?$'
    allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With', 'Accept', 'Origin']
    expose_headers: ['Link', 'X-Total-Count']
    allow_methods: ['GET', 'POST', 'PUT', 'PATCH', 'DELETE', 'OPTIONS']
    max_age: 3600
  paths:
    '^/': ~   # ou '^/api/' si tu veux restreindre aux routes API
