<?php

namespace ContainerO3EUD0i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerendTrajetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gNIDhuY.App\Controller\ApiController::endTrajet()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.gNIDhuY.App\\Controller\\ApiController::endTrajet()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trajet' => ['privates', '.errored..service_locator.gNIDhuY.App\\Entity\\Trajet', NULL, 'Cannot autowire service ".service_locator.gNIDhuY": it needs an instance of "App\\Entity\\Trajet" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mailer' => ['privates', 'mailer.mailer', 'getMailer_MailerService', true],
        ], [
            'trajet' => 'App\\Entity\\Trajet',
            'em' => '?',
            'mailer' => '?',
        ]))->withContext('App\\Controller\\ApiController::endTrajet()', $container);
    }
}
