<?php

namespace ContainerO3EUD0i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiControllerstartTrajetService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fWR6sj8.App\Controller\ApiController::startTrajet()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fWR6sj8.App\\Controller\\ApiController::startTrajet()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'trajet' => ['privates', '.errored..service_locator.fWR6sj8.App\\Entity\\Trajet', NULL, 'Cannot autowire service ".service_locator.fWR6sj8": it needs an instance of "App\\Entity\\Trajet" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'trajet' => 'App\\Entity\\Trajet',
            'em' => '?',
        ]))->withContext('App\\Controller\\ApiController::startTrajet()', $container);
    }
}
