<?php

namespace ContainerO3EUD0i;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getReservationControllermesReservationsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GL345QQ.App\Controller\ReservationController::mesReservations()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.GL345QQ.App\\Controller\\ReservationController::mesReservations()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'serializer' => ['privates', 'debug.serializer', 'getDebug_SerializerService', false],
        ], [
            'serializer' => '?',
        ]))->withContext('App\\Controller\\ReservationController::mesReservations()', $container);
    }
}
