<?php

namespace ContainerI1u346P;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAdminSetupControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\AdminSetupController' shared autowired service.
     *
     * @return \App\Controller\AdminSetupController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'AdminSetupController.php';

        return $container->services['App\\Controller\\AdminSetupController'] = new \App\Controller\AdminSetupController();
    }
}
