<?php

namespace ContainerG8l8P1q;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SIPMNbiService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.sIPMNbi' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.sIPMNbi'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ApiController::getMesTrajets' => ['privates', '.service_locator._4FzYXo.App\\Controller\\ApiController::getMesTrajets()', 'getApiControllergetMesTrajetsService', true],
            'App\\Controller\\ApiController::startTrajet' => ['privates', '.service_locator.fWR6sj8.App\\Controller\\ApiController::startTrajet()', 'getApiControllerstartTrajetService', true],
            'App\\Controller\\ApiController::endTrajet' => ['privates', '.service_locator.gNIDhuY.App\\Controller\\ApiController::endTrajet()', 'getApiControllerendTrajetService', true],
            'App\\Controller\\ApiController::finishTrajet' => ['privates', '.service_locator.qS6acth.App\\Controller\\ApiController::finishTrajet()', 'getApiControllerfinishTrajetService', true],
            'App\\Controller\\AuthController::signup' => ['privates', '.service_locator.u_wbj2I.App\\Controller\\AuthController::signup()', 'getAuthControllersignupService', true],
            'App\\Controller\\AuthController::checkEmail' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AuthController::checkEmail()', 'getAuthControllercheckEmailService', true],
            'App\\Controller\\AuthController::ajouterCredits' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AuthController::ajouterCredits()', 'getAuthControllerajouterCreditsService', true],
            'App\\Controller\\ReservationController::create' => ['privates', '.service_locator.lEKiwLz.App\\Controller\\ReservationController::create()', 'getReservationControllercreateService', true],
            'App\\Controller\\ReservationController::mesReservations' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ReservationController::mesReservations()', 'getReservationControllermesReservationsService', true],
            'App\\Controller\\UserController::listUsers' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::listUsers()', 'getUserControllerlistUsersService', true],
            'App\\Controller\\UserController::checkEmail' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::checkEmail()', 'getUserControllercheckEmailService', true],
            'App\\Controller\\UserController::checkPseudo' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::checkPseudo()', 'getUserControllercheckPseudoService', true],
            'App\\Controller\\UserController::suspendUser' => ['privates', '.service_locator.OA38qqg.App\\Controller\\UserController::suspendUser()', 'getUserControllersuspendUserService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\ApiController:getMesTrajets' => ['privates', '.service_locator._4FzYXo.App\\Controller\\ApiController::getMesTrajets()', 'getApiControllergetMesTrajetsService', true],
            'App\\Controller\\ApiController:startTrajet' => ['privates', '.service_locator.fWR6sj8.App\\Controller\\ApiController::startTrajet()', 'getApiControllerstartTrajetService', true],
            'App\\Controller\\ApiController:endTrajet' => ['privates', '.service_locator.gNIDhuY.App\\Controller\\ApiController::endTrajet()', 'getApiControllerendTrajetService', true],
            'App\\Controller\\ApiController:finishTrajet' => ['privates', '.service_locator.qS6acth.App\\Controller\\ApiController::finishTrajet()', 'getApiControllerfinishTrajetService', true],
            'App\\Controller\\AuthController:signup' => ['privates', '.service_locator.u_wbj2I.App\\Controller\\AuthController::signup()', 'getAuthControllersignupService', true],
            'App\\Controller\\AuthController:checkEmail' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AuthController::checkEmail()', 'getAuthControllercheckEmailService', true],
            'App\\Controller\\AuthController:ajouterCredits' => ['privates', '.service_locator.Kq27LHM.App\\Controller\\AuthController::ajouterCredits()', 'getAuthControllerajouterCreditsService', true],
            'App\\Controller\\ReservationController:create' => ['privates', '.service_locator.lEKiwLz.App\\Controller\\ReservationController::create()', 'getReservationControllercreateService', true],
            'App\\Controller\\ReservationController:mesReservations' => ['privates', '.service_locator.GL345QQ.App\\Controller\\ReservationController::mesReservations()', 'getReservationControllermesReservationsService', true],
            'App\\Controller\\UserController:listUsers' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::listUsers()', 'getUserControllerlistUsersService', true],
            'App\\Controller\\UserController:checkEmail' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::checkEmail()', 'getUserControllercheckEmailService', true],
            'App\\Controller\\UserController:checkPseudo' => ['privates', '.service_locator.OzEre6h.App\\Controller\\UserController::checkPseudo()', 'getUserControllercheckPseudoService', true],
            'App\\Controller\\UserController:suspendUser' => ['privates', '.service_locator.OA38qqg.App\\Controller\\UserController::suspendUser()', 'getUserControllersuspendUserService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\ApiController::getMesTrajets' => '?',
            'App\\Controller\\ApiController::startTrajet' => '?',
            'App\\Controller\\ApiController::endTrajet' => '?',
            'App\\Controller\\ApiController::finishTrajet' => '?',
            'App\\Controller\\AuthController::signup' => '?',
            'App\\Controller\\AuthController::checkEmail' => '?',
            'App\\Controller\\AuthController::ajouterCredits' => '?',
            'App\\Controller\\ReservationController::create' => '?',
            'App\\Controller\\ReservationController::mesReservations' => '?',
            'App\\Controller\\UserController::listUsers' => '?',
            'App\\Controller\\UserController::checkEmail' => '?',
            'App\\Controller\\UserController::checkPseudo' => '?',
            'App\\Controller\\UserController::suspendUser' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\ApiController:getMesTrajets' => '?',
            'App\\Controller\\ApiController:startTrajet' => '?',
            'App\\Controller\\ApiController:endTrajet' => '?',
            'App\\Controller\\ApiController:finishTrajet' => '?',
            'App\\Controller\\AuthController:signup' => '?',
            'App\\Controller\\AuthController:checkEmail' => '?',
            'App\\Controller\\AuthController:ajouterCredits' => '?',
            'App\\Controller\\ReservationController:create' => '?',
            'App\\Controller\\ReservationController:mesReservations' => '?',
            'App\\Controller\\UserController:listUsers' => '?',
            'App\\Controller\\UserController:checkEmail' => '?',
            'App\\Controller\\UserController:checkPseudo' => '?',
            'App\\Controller\\UserController:suspendUser' => '?',
        ]);
    }
}
