<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFKIz4Ni\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFKIz4Ni/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFKIz4Ni.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFKIz4Ni\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFKIz4Ni\App_KernelDevDebugContainer([
    'container.build_hash' => 'FKIz4Ni',
    'container.build_id' => 'bbf73ffc',
    'container.build_time' => 1747858410,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFKIz4Ni');
